name: Deploy School App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: nessi
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            
            cd ~/school
            git fetch origin
            git reset --hard origin/main
            
            cd backend
            npm install
            npm run migrate
            pm2 restart school-backend || pm2 start server.js --name school-backend
            pm2 save

            cd ../adminpanel
            npm install
            npm run build

            cd ../pwa
            npm install
            npm run build

            sudo systemctl restart caddy
            
            echo "Deployment to Mumbai Server Finished Successfully!"
